apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-node
  template:
    metadata:
      labels:
        app: myapp-node
    spec:
      containers:
      - name: myapp-deployment
        image: anuragjoshi01/nodejs-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
