apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: myapp-node 
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 32000
    
    
